// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project_ESP32_DASHBOARD

#ifndef _UI_COMP_ITEM_H
#define _UI_COMP_ITEM_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT item
#define UI_COMP_ITEM_ITEM 0
#define UI_COMP_ITEM_NAME1 1
#define UI_COMP_ITEM_PRICE1 2
#define _UI_COMP_ITEM_NUM 3
lv_obj_t * ui_item_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
