// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project_ESP32_DASHBOARD

#ifndef _SQUARELINE_PROJECT_ESP32_DASHBOARD_UI_H
#define _SQUARELINE_PROJECT_ESP32_DASHBOARD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_HomePanel;
extern lv_obj_t * ui_TemperaturePanel;
extern lv_obj_t * ui_TemperatureImage;
extern lv_obj_t * ui_TempValPanel;
extern lv_obj_t * ui_tempVal;
extern lv_obj_t * ui_tempLabel;
extern lv_obj_t * ui_HumidityPanel;
extern lv_obj_t * ui_HumidityImage;
extern lv_obj_t * ui_HumidityContainer;
void ui_event_humiArc(lv_event_t * e);
extern lv_obj_t * ui_humiArc;
extern lv_obj_t * ui_humiVal;
extern lv_obj_t * ui_HumidityLabel;
extern lv_obj_t * ui_SpeakerPanel;
extern lv_obj_t * ui_lightON;
void ui_event_SwitchRelay(lv_event_t * e);
extern lv_obj_t * ui_SwitchRelay;
extern lv_obj_t * ui_lightOFF;
extern lv_obj_t * ui_CO2Panel;
void ui_event_mq9Arc(lv_event_t * e);
extern lv_obj_t * ui_mq9Arc;
extern lv_obj_t * ui_mq9Val;
extern lv_obj_t * ui_CO2Label;
extern lv_obj_t * ui_AirQualityPanel;
void ui_event_mq135Arc(lv_event_t * e);
extern lv_obj_t * ui_mq135Arc;
extern lv_obj_t * ui_mq135Val;
extern lv_obj_t * ui_AirQualityLabel;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_temp_icon_png);    // assets/temp_icon.png
LV_IMG_DECLARE(ui_img_img_humi_png);    // assets/img_humi.png
LV_IMG_DECLARE(ui_img_bulb_on_png);    // assets/bulb_on.png
LV_IMG_DECLARE(ui_img_bulb_off_png);    // assets/bulb_off.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
